In [10]:
from mxnet import nd
import mxnet as mx
import numpy as np
import time

In [11]:
# NDArray from tuples
mx.nd.array(((1,2,3),(5,6,7)))


[[1. 2. 3.]
 [5. 6. 7.]]
<NDArray 2x3 @cpu(0)>

In [12]:
# NDArray from ones 
x = nd.ones(shape=(2,3))
x


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [13]:
# Random
y = nd.random.uniform(low=-1,high=1, shape=(2,3))
y


[[ 0.08976638  0.6945034  -0.15269041]
 [ 0.24712741  0.29178822 -0.23123658]]
<NDArray 2x3 @cpu(0)>

In [14]:
# Shape, Size, Type, Where it stored CPU or GPU
(x.shape, x.size, x.dtype, x.context)

((2, 3), 6, numpy.float32, cpu(0))

Type 

In [15]:
nd.ones((2,3), dtype = np.uint8)


[[1 1 1]
 [1 1 1]]
<NDArray 2x3 @cpu(0)>

In [16]:
y.astype(np.float16)


[[ 0.0898  0.6943 -0.1527]
 [ 0.2471  0.2917 -0.2312]]
<NDArray 2x3 @cpu(0)>

## Context
Where the variable will be stored in CPU or GPU memory

In [17]:
nd.ones((2,3), ctx=mx.cpu())


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [18]:
nd.ones((2,3), ctx=mx.gpu())


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @gpu(0)>

## Speed

In [19]:
x_np, y_np = np.ones((1000,5000)), np.ones((5000, 1000))
x_nd_cpu, y_nd_cpu = nd.ones((1000,5000), ctx=mx.cpu()) , nd.ones((5000,1000), ctx=mx.cpu())
x_nd_gpu, y_nd_gpu = nd.ones((10000,5000), ctx=mx.gpu(0)) , nd.ones((5000,10000), ctx=mx.gpu(0))

In [11]:
tic = time.time()
np.dot(x_np, y_np)
print(f"Numpy time {time.time()-tic:.4f}s")

Numpy time 25.3031s


In [12]:
tic = time.time()
np.dot(x_nd_cpu, y_nd_cpu).wait_to_read()
print(f"MXNet CPU time {time.time()-tic:.4f}s")

Exception ignored in: <function NDArrayBase.__del__ at 0x000001631EAF29D0>
Traceback (most recent call last):
  File "d:\Education\Cloud Computing\aws\Coursera - AWS Computer Vision Getting Started with GluonCV\MXNet-GlounCV\lib\site-packages\mxnet\_ctypes\ndarray.py", line 51, in __del__
    check_call(_LIB.MXNDArrayFree(self.handle))
KeyboardInterrupt: 


In [20]:
tic = time.time()
np.dot(x_nd_gpu, y_nd_gpu).wait_to_read()
print(f"MXNet GPU time {time.time()-tic:.4f}s")

Convert from MXNet NDArray and NumPy

In [ ]:
a = x.asnumpy()
(type(a), a)

In [ ]:
nd.array(a)